name = "face-brighten"
pages_build_output_dir = "dist"
compatibility_date = "2025-09-01"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "image-processing"
